spring.application.name=lovable
spring.application.version=1.0.0
server.servlet.context-path=/api
server.port=8080
server.address=0.0.0.0
# session
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/
server.servlet.session.timeout=10d
spring.session.data.redis.namespace=spring:session
# database
spring.datasource.url=jdbc:postgresql://localhost:5432/lovable_db
spring.datasource.username=ashish
spring.datasource.password=ashish
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
# hikari
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
# actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# minio
minio.endpoint=http://localhost:9000
minio.access-key=ashish
minio.secret-key=ashish123
minio.bucket-name=lovablebucket
# logging
logging.level.root=INFO
logging.level.com.lovable=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework.boot.web=INFO
logging.level.org.springframework.boot.actuate=INFO
logging.level.org.springframework.ai=DEBUG
# spring AI
#spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.model=gpt-5.6-luna
#spring.ai.openai.api-key=${NVIDIA_API_KEY}
#spring.ai.openai.model=nvidia/nemotron-3-super-120b-a12b
spring.ai.openai.api-key=${AI_API_KEY}
# shutdown
spring.lifecycle.timeout-per-shutdown-phase=30s
# custom
app.security.remember-me-key=34ok5j6h7g8fd9icbnbcvntr7394cx039c4n7umx3945867b8930
# razorpay
razorpay.key_id=rzp_test_THFFAiHiDGqBqK
razorpay.key_secret=o60si9UAsPT9o6mOuYOcwhn8
razorpay.webhook-secret=0b97d4c9d4f5c16f6a2f3a7b9e1c0d4a6f7e8b9c0d1e2f3a4b5c6d7e8f9a0b1
